USE products_db;

INSERT INTO product_categories (name, description)
VALUES ('Smartphone', 'Mobile phones with advanced OS'),
    ('Tablet', 'Touchscreen mobile computing devices'),
    ('Smartwatch', 'Wearable smart devices'),
    ('Laptop', 'Portable personal computers'),
    ('Desktop PC', 'Stationary personal computers'),
    ('All-in-One PC', 'Integrated desktop computers'),
    ('Mini PC', 'Compact small-form-factor computers'),
    ('Gaming PC', 'Performance systems for gaming'),
    ('Server', 'Enterprise and data center servers'),
    ('Monitor', 'Computer display devices'),
    ('CPU', 'Central processing units'),
    ('GPU', 'Graphics processors units'),
    ('Motherboard', 'Main logic boards'),
    ('RAM', 'System memory modules'),
    ('Storage', 'SSD, HDD, storage devices'),
    ('Power Supply', 'Computer power delivery units'),
    ('Computer Case', 'PC chassis and enclosures'),
    ('Network Device', 'Routers and wireless devices'),
    ('Keyboard', 'Input keyboard devices'),
    ('Mouse', 'Input pointing devices'),
    ('Headphones', 'Audio listening devices'),
    ('Speakers', 'External audio output devices'),
    ('Microphone', 'Audio recording devices'),
    ('Webcam', 'Camera devices for video calls'),
    ('Printer', 'Document printing devices'),
    ('Scanner', 'Document scanning devices');